language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests aaaa"

script:
  - docker --version # print the version for logging
  - docker build -t travis-ci .
  - docker tag travis-ci 15061991/travis-ci:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push 15061991/travis-ci
